# Generated by Django 5.1.6 on 2025-02-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='category',
            new_name='Category',
        ),
    ]
