# Generated by Django 5.1.6 on 2025-02-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_category_record_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Category',
            new_name='category',
        ),
    ]
